# Generated by Django 3.2.4 on 2021-11-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readAt',
            field=models.DateTimeField(null=True),
        ),
    ]
